site_name: gocryptfs
theme: readthedocs
theme_dir: xreadthedocs
pages:
- Home: index.md
- Quickstart: quickstart.md
- Compile from Source: compile.md
- Security: security.md
- Reverse Mode: reverse_mode.md
- Comparison with Other Projects: comparison.md
- Signed Releases: releases.md
- Source Code Mirrors: mirrors.md
