site_name: gocryptfs
theme: readthedocs
theme_dir: xreadthedocs
pages:
- Home: index.md
- Quickstart: quickstart.md
- Compile from Source: compile.md
- Cryptography: forward_mode_crypto.md
- Reverse Mode Cryptography: reverse_mode_crypto.md
- Comparison with Other Projects: comparison.md
- Signed Releases: releases.md
- Source Code Mirrors: mirrors.md
- Contribute: contribute.md
