site_name: gocryptfs
theme: readthedocs
theme_dir: xreadthedocs
pages:
- Home: index.md
- Quickstart: quickstart.md
- Security: security.md
- Comparison with Other Projects: comparison.md
- Signed Releases: releases.md
